import type { Prompt } from '../types';

export const prompts: Prompt[] = [
  // === PLANIFICACIÓN FAMILIAR ===
  {
    id: 1,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Menú Semanal Automático',
    description: 'Planificador inteligente de comidas familiares',
    prompt: 'Soy madre de [X] hijos de [edades], presupuesto semanal $[cantidad], tiempo de cocina máximo [X] minutos, alimentos que NO comen: [lista]. Crea menú 7 días nutritivo + lista compras por secciones del supermercado.',
    timeSaved: '3 horas/semana',
    urgency: 'ALTA',
    implementation: '5 minutos setup',
  },
  {
    id: 2,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Lista de Compras Inteligente',
    description: 'Generador automático optimizado por rutas',
    prompt: 'Necesito lista de compras para familia de [X], presupuesto $[X], supermercado [nombre], priorizar: productos frescos, evitar: [alergias]. Organiza por pasillos y sugiere alternativas económicas.',
    timeSaved: '45 min/compra',
    urgency: 'ALTA',
    implementation: '3 minutos setup',
  },
  {
    id: 3,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Rutina Matutina Familiar',
    description: 'Optimizador de mañanas sin estrés',
    prompt: 'Familia: [composición], horarios salida: [hora], tiempo disponible: [X] min. Diseña rutina matutina realista que incluya: desayuno, preparación niños, tiempo personal. Considera días escolares vs fines de semana.',
    timeSaved: '1 hora/mañana',
    urgency: 'ALTA',
    implementation: '10 minutos setup',
  },
  {
    id: 4,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Calendario de Actividades Infantiles',
    description: 'Planificador de entretenimiento por edades',
    prompt: 'Niños de [edades], tiempo disponible [X] minutos, ubicación: [casa/exterior], materiales: [básicos], objetivo: [desarrollo/entretenimiento]. Sugiere 5 actividades apropiadas con instrucciones paso a paso.',
    timeSaved: '30 min/día',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 5,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Presupuesto Familiar Automático',
    description: 'Controlador de gastos inteligente',
    prompt: 'Ingresos mensuales: $[X], gastos fijos: [lista], número hijos: [X], objetivos ahorro: [X]. Crea presupuesto realista con alertas automáticas y sugerencias de optimización.',
    timeSaved: '2 horas/mes',
    urgency: 'ALTA',
    implementation: '15 minutos setup',
  },
  {
    id: 6,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Organizador de Citas Médicas',
    description: 'Gestor de salud familiar',
    prompt: 'Familia de [X] miembros, edades: [X], médicos frecuentes: [pediatra, dentista, etc.], recordatorios necesarios: [vacunas, controles]. Crea sistema de seguimiento y recordatorios automáticos.',
    timeSaved: '1 hora/mes',
    urgency: 'MEDIA',
    implementation: '10 minutos setup',
  },
  {
    id: 7,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Planificador de Fin de Semana',
    description: 'Optimizador de tiempo familiar',
    prompt: 'Fin de semana disponible: [sábado/domingo], presupuesto: $[X], edades niños: [X], intereses familia: [lista]. Sugiere plan equilibrado: diversión + descanso + tareas necesarias.',
    timeSaved: '45 min/semana',
    urgency: 'BAJA',
    implementation: '5 minutos setup',
  },
  {
    id: 8,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Preparación de Vacaciones Familiares',
    description: 'Organizador de viajes sin estrés',
    prompt: 'Destino: [X], duración: [X] días, edades: [X], presupuesto: [X]. Crea checklist completo: documentos, equipaje por edad, actividades, emergencias, itinerario flexible.',
    timeSaved: '3 horas/viaje',
    urgency: 'BAJA',
    implementation: '20 minutos setup',
  },
  {
    id: 9,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Delegador de Tareas Domésticas',
    description: 'Asigna tareas a los niños según su edad',
    prompt: 'Tengo hijos de [edades]. Necesito un sistema de tareas domésticas que sea justo, educativo y fácil de supervisar. Crea una tabla de responsabilidades semanales para cada uno, con un sistema de recompensas que no sea monetario.',
    timeSaved: '1.5 horas/semana',
    urgency: 'MEDIA',
    implementation: '15 minutos setup',
  },
  {
    id: 10,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Planificador de Metas Familiares',
    description: 'Define y sigue objetivos como familia',
    prompt: 'Somos una familia con hijos de [edades]. Queremos establecer 3 metas para el próximo trimestre en las áreas de [ej: salud, aprendizaje, conexión]. Define metas SMART y crea un plan de acción semanal para alcanzarlas juntos.',
    timeSaved: '1 hora/trimestre',
    urgency: 'BAJA',
    implementation: '20 minutos setup',
  },
  {
    id: 11,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Optimizador de Logística Escolar',
    description: 'Gestiona horarios, rutas y materiales',
    prompt: 'Tengo [X] hijos en [grados/colegios]. Sus horarios son [lista]. Necesito optimizar la logística de transporte, extraescolares y preparación de mochilas. Crea un "centro de comando" visual para la semana.',
    timeSaved: '2 horas/semana',
    urgency: 'ALTA',
    implementation: '15 minutos setup',
  },
  {
    id: 12,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Gestor de Documentos Importantes',
    description: 'Organiza digitalmente papeles esenciales',
    prompt: 'Necesito un sistema para organizar digitalmente los documentos de mi familia ([actas de nacimiento, pasaportes, seguros, carnets de vacunación]). Sugiere una estructura de carpetas y un método de nombrado para tener todo accesible y seguro.',
    timeSaved: '3 horas/año',
    urgency: 'MEDIA',
    implementation: '30 minutos setup',
  },

  // === CRIANZA Y EDUCACIÓN ===
  {
    id: 13,
    category: 'CRIANZA Y EDUCACIÓN',
    tool: 'Resolvedor de Conflictos entre Hermanos',
    description: 'IA para mediar peleas entre hermanos',
    prompt: 'Situación: [descripción conflicto], edades involucradas: [X], personalidades: [descripción]. Necesito 3 estrategias inmediatas para resolver sin gritos, explicando por qué funcionarán con estos niños específicos.',
    timeSaved: '45 min/día',
    urgency: 'ALTA',
    implementation: '2 minutos setup',
  },
  {
    id: 14,
    category: 'CRIANZA Y EDUCACIÓN',
    tool: 'Generador de Consecuencias Lógicas',
    description: 'Sistema disciplinario respetuoso',
    prompt: 'Mi hijo de [edad] hizo [comportamiento], contexto: [situación]. Sugiere consecuencia lógica que enseñe sin castigar, apropiada para su desarrollo y que fortalezca nuestra relación.',
    timeSaved: '30 min/episodio',
    urgency: 'ALTA',
    implementation: '3 minutos setup',
  },
  {
    id: 15,
    category: 'CRIANZA Y EDUCACIÓN',
    tool: 'Apoyo para Tareas Escolares',
    description: 'Asistente educativo personalizado',
    prompt: 'Materia: [X], grado: [X], dificultad específica: [X], estilo aprendizaje del niño: [visual/auditivo/kinestésico]. Explica concepto de manera simple y sugiere actividad práctica para reforzar.',
    timeSaved: '1 hora/día',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 16,
    category: 'CRIANZA Y EDUCACIÓN',
    tool: 'Detector de Necesidades Emocionales',
    description: 'Intérprete de comportamientos',
    prompt: 'Mi hijo de [edad] está mostrando: [comportamientos observados], cambios recientes: [contexto]. Ayúdame a entender qué necesidad emocional no está cubierta y cómo responder empáticamente.',
    timeSaved: '20 min/episodio',
    urgency: 'ALTA',
    implementation: '2 minutos setup',
  },
  {
    id: 17,
    category: 'CRIANZA Y EDUCACIÓN',
    tool: 'Planificador de Tiempo de Calidad',
    description: 'Optimizador de conexión familiar',
    prompt: 'Tiempo disponible: [X] minutos, edad del niño: [X], su interés actual: [X], mi energía: [nivel 1-10]. Sugiere actividad específica que fortalezca nuestro vínculo y sea significativa para ambos.',
    timeSaved: 'Variable',
    urgency: 'MEDIA',
    implementation: '3 minutos setup',
  },
  {
    id: 18,
    category: 'CRIANZA Y EDUCACIÓN',
    tool: 'Traductor de Rabietas',
    description: 'Decodificador emocional infantil',
    prompt: 'Edad: [X], situación de la rabieta: [contexto], intensidad: [1-10], duración: [tiempo]. Explica qué está comunicando realmente y dame estrategia específica para acompañar sin ceder ni controlar.',
    timeSaved: '30 min/episodio',
    urgency: 'ALTA',
    implementation: '2 minutos setup',
  },
  {
    id: 19,
    category: 'CRIANZA Y EDUCACIÓN',
    tool: 'Fomentador de Independencia',
    description: 'Guía de autonomía por edades',
    prompt: 'Edad: [X], habilidad a desarrollar: [X], nivel actual del niño: [descripción]. Crea plan gradual de 2 semanas para que desarrolle esta habilidad sin frustración, con pasos específicos diarios.',
    timeSaved: 'Variable',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 20,
    category: 'CRIANZA Y EDUCACIÓN',
    tool: 'Comunicador para Temas Difíciles',
    description: 'Traductor de lenguaje infantil',
    prompt: 'Necesito hablar con mi hijo de [edad] sobre: [tema difícil], su personalidad: [descripción]. Dame guión adaptado a su comprensión que sea honesto, apropiado y que invite al diálogo.',
    timeSaved: '15 min/conversación',
    urgency: 'ALTA',
    implementation: '3 minutos setup',
  },
  {
    id: 21,
    category: 'CRIANZA Y EDUCACIÓN',
    tool: 'Generador de Cuentos Personalizados',
    description: 'Crea historias con tus hijos como protagonistas',
    prompt: 'Crea un cuento corto para mi hijo/a de [edad] llamado/a [nombre]. El tema es [ej: el miedo a la oscuridad] y sus personajes favoritos son [lista]. La historia debe enseñar [lección] de forma sutil.',
    timeSaved: '20 min/cuento',
    urgency: 'BAJA',
    implementation: '2 minutos setup',
  },
  {
    id: 22,
    category: 'CRIANZA Y EDUCACIÓN',
    tool: 'Adaptador de Actividades Educativas',
    description: 'Convierte cualquier tema en un juego',
    prompt: 'Mi hijo de [edad] necesita aprender sobre [tema académico, ej: las tablas de multiplicar]. Su gran interés es [hobby, ej: los dinosaurios]. Diseña 3 actividades lúdicas que conecten ambos temas.',
    timeSaved: '45 min/actividad',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 23,
    category: 'CRIANZA Y EDUCACIÓN',
    tool: 'Gestor de Límites de Pantalla',
    description: 'Establece reglas de uso de tecnología',
    prompt: 'Familia con hijos de [edades]. Necesitamos un plan de uso de pantallas que sea claro y consistente. Define reglas sobre tiempos, lugares y contenidos, y crea un "contrato familiar tecnológico" para firmar todos.',
    timeSaved: '3 horas/discusión',
    urgency: 'ALTA',
    implementation: '10 minutos setup',
  },
  {
    id: 24,
    category: 'CRIANZA Y EDUCACIÓN',
    tool: 'Coach de Habilidades Sociales',
    description: 'Ayuda a tus hijos a hacer amigos',
    prompt: 'Mi hijo de [edad] es [tímido/impulsivo] y le cuesta [hacer amigos/resolver conflictos]. Describe 3 escenarios de juego de roles que podemos practicar en casa para desarrollar la habilidad de [empatía/compartir/iniciar conversaciones].',
    timeSaved: 'Variable',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },

  // === HOGAR Y ORGANIZACIÓN ===
  {
    id: 25,
    category: 'HOGAR Y ORGANIZACIÓN',
    tool: 'Sistema de Limpieza Inteligente',
    description: 'Optimizador de tareas domésticas',
    prompt: 'Casa de [X] habitaciones, [X] habitantes, mascotas: [sí/no], tiempo disponible: [X] horas/semana. Crea rutina de limpieza realista dividida por días, priorizando áreas críticas y optimizando esfuerzo.',
    timeSaved: '5 horas/semana',
    urgency: 'ALTA',
    implementation: '10 minutos setup',
  },
  {
    id: 26,
    category: 'HOGAR Y ORGANIZACIÓN',
    tool: 'Organizador de Espacios (Método KonMari AI)',
    description: 'Consultor de orden y funcionalidad',
    prompt: 'Espacio a organizar: [habitación], problema principal: [descripción], presupuesto: $[X], niños que usan el espacio: [edades]. Diseña sistema de organización que sea fácil de mantener por toda la familia.',
    timeSaved: '2 horas/espacio',
    urgency: 'MEDIA',
    implementation: '15 minutos setup',
  },
  {
    id: 27,
    category: 'HOGAR Y ORGANIZACIÓN',
    tool: 'Planificador de Mantenimiento del Hogar',
    description: 'Calendario preventivo del hogar',
    prompt: 'Tipo de vivienda: [casa/apto], antigüedad: [años], electrodomésticos: [lista], última revisión: [cuándo]. Crea cronograma anual de mantenimiento con recordatorios mensuales y presupuesto estimado.',
    timeSaved: '3 horas/año',
    urgency: 'BAJA',
    implementation: '20 minutos setup',
  },
  {
    id: 28,
    category: 'HOGAR Y ORGANIZACIÓN',
    tool: 'Optimizador de Lavandería Familiar',
    description: 'Automatizador de ropa familiar',
    prompt: 'Familia de [X] personas, frecuencia lavado: [X] veces/semana, tipo de ropa predominante: [casual/formal/mixta]. Crea sistema eficiente: clasificación, horarios, doblado y guardado que funcione para todos.',
    timeSaved: '3 horas/semana',
    urgency: 'ALTA',
    implementation: '5 minutos setup',
  },
  {
    id: 29,
    category: 'HOGAR Y ORGANIZACIÓN',
    tool: 'Controlador de Inventarios (Despensa y Limpieza)',
    description: 'Gestor de despensa y suministros',
    prompt: 'Tamaño familia: [X], espacio almacenamiento: [descripción], presupuesto mensual: $[X]. Crea sistema de control de stock con alertas automáticas y lista de compras inteligente.',
    timeSaved: '1 hora/mes',
    urgency: 'MEDIA',
    implementation: '15 minutos setup',
  },
  {
    id: 30,
    category: 'HOGAR Y ORGANIZACIÓN',
    tool: 'Coordinador de Agenda Familiar',
    description: 'Sincronizador de horarios y actividades',
    prompt: 'Miembros familia: [X], actividades regulares: [lista], vehículos disponibles: [X]. Optimiza logística familiar, detecta conflictos de horarios y sugiere soluciones de transporte.',
    timeSaved: '2 horas/semana',
    urgency: 'ALTA',
    implementation: '10 minutos setup',
  },
  {
    id: 31,
    category: 'HOGAR Y ORGANIZACIÓN',
    tool: 'Digitalizador de Recuerdos (Fotos y Dibujos)',
    description: 'Conserva los tesoros de tus hijos sin ocupar espacio',
    prompt: 'Tengo [cientos] de [dibujos/fotos] de mis hijos. Sugiere un flujo de trabajo para digitalizarlos (apps de escaneo, almacenamiento en la nube) y un sistema para crear álbumes digitales temáticos.',
    timeSaved: '10 horas/año',
    urgency: 'BAJA',
    implementation: '1 hora setup',
  },
  {
    id: 32,
    category: 'HOGAR Y ORGANIZACIÓN',
    tool: 'Gestor de "Destrashing" o Depuración',
    description: 'Crea un plan para deshacerte de lo que no necesitas',
    prompt: 'Quiero depurar mi casa, pero me siento abrumada. El área más caótica es [habitación]. Crea un plan de 30 días, con una micro-tarea de 15 minutos diarios, para organizar y donar/tirar lo innecesario.',
    timeSaved: 'Variable',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 33,
    category: 'HOGAR Y ORGANIZACIÓN',
    tool: 'Planificador de Mudanzas',
    description: 'Organiza una mudanza familiar sin estrés',
    prompt: 'Nos mudamos en [X] semanas a una casa de [tamaño]. Somos [X] en la familia. Crea un checklist completo por semanas, desde la depuración inicial hasta el desempaque, incluyendo un sistema de etiquetado de cajas por habitación.',
    timeSaved: '20 horas/mudanza',
    urgency: 'ALTA',
    implementation: '30 minutos setup',
  },
  {
    id: 34,
    category: 'HOGAR Y ORGANIZACIÓN',
    tool: 'Optimizador de Espacios Pequeños',
    description: 'Maximiza cada rincón de tu hogar',
    prompt: 'Vivo en un [apartamento/casa pequeña]. El espacio más problemático es [habitación] que mide [dimensiones]. Sugiere 5 soluciones de almacenamiento inteligentes y multifuncionales para maximizar el espacio vertical y horizontal.',
    timeSaved: '5 horas/investigación',
    urgency: 'MEDIA',
    implementation: '10 minutos setup',
  },
  {
    id: 35,
    category: 'HOGAR Y ORGANIZACIÓN',
    tool: 'Creador de Zonas Funcionales en Casa',
    description: 'Define áreas para trabajo, juego y descanso',
    prompt: 'Necesito crear una zona de [trabajo/juego/lectura] en mi [sala/dormitorio]. El espacio disponible es [descripción]. Diseña cómo delimitar y organizar esta zona con el mobiliario que ya tengo para que sea funcional y estéticamente agradable.',
    timeSaved: '3 horas/diseño',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 36,
    category: 'HOGAR Y ORGANIZACIÓN',
    tool: 'Sistema de Rotación de Juguetes',
    description: 'Reduce el desorden y aumenta el interés por el juego',
    prompt: 'Mis hijos de [edades] tienen demasiados juguetes y siempre está todo desordenado. Diseña un sistema de rotación de juguetes en 3 pasos: clasificar, almacenar y rotar, para mantener el orden y renovar su interés.',
    timeSaved: '3 horas/mes',
    urgency: 'MEDIA',
    implementation: '1 hora setup',
  },

  // === AUTOCUIDADO Y BIENESTAR ===
  {
    id: 37,
    category: 'AUTOCUIDADO Y BIENESTAR',
    tool: 'Detector de Señales de Agotamiento (Burnout)',
    description: 'Monitor de señales de burnout maternal',
    prompt: 'Síntomas que siento: [lista], duración: [tiempo], cambios en mi comportamiento: [descripción], apoyo disponible: [nivel]. Analiza mi estado, identifica riesgo de burnout y sugiere plan de acción inmediato.',
    timeSaved: '2 horas/día',
    urgency: 'ALTA',
    implementation: '3 minutos setup',
  },
  {
    id: 38,
    category: 'AUTOCUIDADO Y BIENESTAR',
    tool: 'Planificador de Tiempo Personal ("Mamá Time")',
    description: 'Optimizador de momentos para mamá',
    prompt: 'Tiempo real disponible: [X] minutos, energía actual: [1-10], necesidad emocional: [relajación/activación/conexión]. Sugiere actividad específica de autocuidado que sea realista y realmente efectiva para mi estado actual.',
    timeSaved: 'Variable',
    urgency: 'ALTA',
    implementation: '2 minutos setup',
  },
  {
    id: 39,
    category: 'AUTOCUIDADO Y BIENESTAR',
    tool: 'Gestor de Límites Saludables (Asistente para decir "NO")',
    description: 'Asistente para decir NO sin culpa',
    prompt: 'Situación: [descripción petición], mi capacidad actual: [%], consecuencias de aceptar: [lista], relación con quien pide: [tipo]. Ayúdame a evaluar y dame script respetuoso para responder.',
    timeSaved: '30 min/decisión',
    urgency: 'ALTA',
    implementation: '2 minutos setup',
  },
  {
    id: 40,
    category: 'AUTOCUIDADO Y BIENESTAR',
    tool: 'Optimizador de Energía Maternal',
    description: 'Administrador de recursos personales',
    prompt: 'Hora del día: [X], nivel energía: [1-10], tareas pendientes: [lista], tiempo hasta siguiente break: [X] min. Prioriza tareas según mi energía y sugiere micro-descansos estratégicos.',
    timeSaved: '1 hora/día',
    urgency: 'MEDIA',
    implementation: '3 minutos setup',
  },
  {
    id: 41,
    category: 'AUTOCUIDADO Y BIENESTAR',
    tool: 'Consejero de Redes de Apoyo',
    description: 'Activador de ayuda externa',
    prompt: 'Situación actual: [descripción estrés], personas disponibles: [lista], tipo de ayuda que necesito: [específica]. Identifica mejor opción de apoyo y dame script para pedir ayuda sin sentirme culpable.',
    timeSaved: '45 min/crisis',
    urgency: 'ALTA',
    implementation: '5 minutos setup',
  },
  {
    id: 42,
    category: 'AUTOCUIDADO Y BIENESTAR',
    tool: 'Tracker de Bienestar Integral (Sueño, Nutrición, Ejercicio)',
    description: 'Monitor holístico de salud maternal',
    prompt: 'Sueño: [horas/calidad], alimentación: [descripción], ejercicio: [frecuencia], conexiones sociales: [nivel], tiempo personal: [cantidad]. Evalúa mi bienestar integral y sugiere 1 cambio específico prioritario.',
    timeSaved: 'Variable',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 43,
    category: 'AUTOCUIDADO Y BIENESTAR',
    tool: 'Generador de Afirmaciones Positivas',
    description: 'Crea mantras personalizados para mamás',
    prompt: 'Estoy luchando con sentimientos de [culpa/insuficiencia/impaciencia]. Genera 5 afirmaciones positivas cortas y poderosas que pueda repetir durante el día para contrarrestar estos pensamientos.',
    timeSaved: '10 min/día',
    urgency: 'MEDIA',
    implementation: '1 minuto setup',
  },
  {
    id: 44,
    category: 'AUTOCUIDADO Y BIENESTAR',
    tool: 'Coach de Mindfulness para Madres Ocupadas',
    description: 'Técnicas de 5 minutos para encontrar la calma',
    prompt: 'Necesito una técnica de mindfulness que pueda hacer en menos de 5 minutos mientras [los niños juegan/espero en el coche]. Guíame paso a paso en un ejercicio para reducir el estrés y reconectar conmigo misma.',
    timeSaved: 'Variable',
    urgency: 'ALTA',
    implementation: '1 minuto setup',
  },
  {
    id: 45,
    category: 'AUTOCUIDADO Y BIENESTAR',
    tool: 'Planificador de Citas Personales (Médicas, Belleza)',
    description: 'Asegura que tu salud y bienestar también cuenten',
    prompt: 'Como madre, siempre pospongo mis propias citas. Mis necesidades son [chequeo médico, dentista, corte de pelo]. Analiza la agenda familiar [pegar horarios] y encuentra 3 posibles huecos en las próximas 4 semanas para agendarlas.',
    timeSaved: '1 hora/mes',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 46,
    category: 'AUTOCUIDADO Y BIENESTAR',
    tool: 'Identificador de "Ladrones de Alegría"',
    description: 'Descubre qué actividades o personas drenan tu energía',
    prompt: 'Me siento agotada emocionalmente. Ayúdame a identificar posibles "ladrones de alegría". Guíame con 5 preguntas reflexivas sobre mis interacciones y actividades diarias para descubrir qué me está drenando.',
    timeSaved: '30 min/semana',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 47,
    category: 'AUTOCUIDADO Y BIENESTAR',
    tool: 'Creador de Rituales de Relajación',
    description: 'Diseña una rutina para antes de dormir',
    prompt: 'Me cuesta desconectar por la noche. Tengo 20 minutos después de que los niños se duermen. Diseña un ritual de relajación simple, sin pantallas, que me ayude a bajar revoluciones y prepararme para un sueño reparador.',
    timeSaved: 'Variable',
    urgency: 'MEDIA',
    implementation: '3 minutos setup',
  },
  {
    id: 48,
    category: 'AUTOCUIDADO Y BIENESTAR',
    tool: 'Diario Guiado de Gratitud',
    description: 'Enfócate en lo positivo en 5 minutos',
    prompt: 'Hoy fue un día difícil. Genera 3 preguntas específicas de gratitud que me ayuden a encontrar aspectos positivos en mi día como madre, incluso cuando me siento abrumada.',
    timeSaved: '15 min/día',
    urgency: 'BAJA',
    implementation: '1 minuto setup',
  },

  // === EMERGENCIAS Y SOLUCIONES RÁPIDAS ===
  {
    id: 49,
    category: 'EMERGENCIAS Y SOLUCIONES RÁPIDAS',
    tool: 'Kit de Supervivencia para Días Caóticos',
    description: 'Protocolo para días completamente caóticos',
    prompt: 'Situación actual: [descripción caos], tiempo disponible: [X] minutos, prioridad absoluta hoy: [1 cosa], energía personal: [1-10]. Dame plan de supervivencia de 3 pasos que mantenga lo esencial funcionando.',
    timeSaved: '2 horas/crisis',
    urgency: 'CRÍTICA',
    implementation: '1 minuto setup',
  },
  {
    id: 50,
    category: 'EMERGENCIAS Y SOLUCIONES RÁPIDAS',
    tool: 'Solucionador de Crisis Infantiles (Accidentes, Miedos)',
    description: 'Respuesta inmediata a emergencias de crianza',
    prompt: 'Emergencia: [descripción situación], edad del niño: [X], ubicación: [casa/fuera], personas presentes: [quién]. Necesito protocolo inmediato paso a paso para manejar la situación de forma segura y calmada.',
    timeSaved: 'Variable',
    urgency: 'CRÍTICA',
    implementation: '30 segundos setup',
  },
  {
    id: 51,
    category: 'EMERGENCIAS Y SOLUCIONES RÁPIDAS',
    tool: 'Plan B Automático (para cuando todo falla)',
    description: 'Backup instantáneo para cuando todo falla',
    prompt: 'Qué falló: [situación], tiempo hasta obligación: [X] minutos, recursos disponibles: [lista mínima]. Genera plan B realista que funcione con recursos limitados y tiempo escaso.',
    timeSaved: '1 hora/crisis',
    urgency: 'CRÍTICA',
    implementation: '1 minuto setup',
  },
  {
    id: 52,
    category: 'EMERGENCIAS Y SOLUCIONES RÁPIDAS',
    tool: 'Gestor de Agobio Agudo (Overwhelm)',
    description: 'Protocolo para sobrecarga emocional extrema',
    prompt: 'Me siento: [emociones], síntomas físicos: [lista], situación desencadenante: [contexto], apoyo inmediato: [disponible/no]. Dame protocolo de 5 minutos para estabilizarme y plan de las próximas 2 horas.',
    timeSaved: 'Variable',
    urgency: 'CRÍTICA',
    implementation: '30 segundos setup',
  },
  {
    id: 53,
    category: 'EMERGENCIAS Y SOLUCIONES RÁPIDAS',
    tool: 'Activador de Red de Emergencia',
    description: 'Llamada de auxilio estructurada',
    prompt: 'Necesito ayuda urgente con: [específico], tiempo crítico: [cuándo], personas que podrían ayudar: [lista]. Prioriza contactos y dame scripts específicos para pedir ayuda efectivamente.',
    timeSaved: '30 min/crisis',
    urgency: 'CRÍTICA',
    implementation: '2 minutos setup',
  },
  {
    id: 54,
    category: 'EMERGENCIAS Y SOLUCIONES RÁPIDAS',
    tool: 'Simplificador Extremo (Reducción a lo esencial)',
    description: 'Reducción a lo absolutamente esencial',
    prompt: 'Todo está colapsando: [descripción], debo mantener: [obligaciones críticas], puedo posponer: [lista]. Identifica solo las 3 cosas más críticas para las próximas 24 horas y elimina todo lo demás.',
    timeSaved: 'Variable',
    urgency: 'CRÍTICA',
    implementation: '2 minutos setup',
  },
  {
    id: 55,
    category: 'EMERGENCIAS Y SOLUCIONES RÁPIDAS',
    tool: 'Botiquín de Primeros Auxilios Emocionales',
    description: 'Recursos rápidos para calmar una crisis emocional infantil',
    prompt: 'Mi hijo de [edad] está teniendo una crisis emocional por [motivo]. Necesito 3 técnicas de co-regulación que pueda aplicar ahora mismo para ayudarle a calmarse.',
    timeSaved: '20 min/crisis',
    urgency: 'CRÍTICA',
    implementation: '1 minuto setup',
  },
  {
    id: 56,
    category: 'EMERGENCIAS Y SOLUCIONES RÁPIDAS',
    tool: 'Generador de Respuestas Rápidas para Preguntas Incómodas',
    description: 'Sal del paso ante comentarios sobre tu crianza',
    prompt: 'Un [familiar/desconocido] me acaba de hacer un comentario incómodo sobre [tema de crianza]. Necesito una respuesta corta, educada pero firme para establecer un límite sin crear un gran conflicto.',
    timeSaved: '15 min/interacción',
    urgency: 'ALTA',
    implementation: '30 segundos setup',
  },
  {
    id: 57,
    category: 'EMERGENCIAS Y SOLUCIONES RÁPIDAS',
    tool: 'Solucionador de "No sé qué cenar"',
    description: 'Crea una cena rápida con lo que tienes a mano',
    prompt: 'Son las 7pm, no tengo plan de cena. En mi nevera tengo [ingrediente 1, 2, 3] y en la despensa [ingrediente 4, 5, 6]. Dame 3 opciones de cena que pueda preparar en menos de 20 minutos.',
    timeSaved: '30 min/día',
    urgency: 'CRÍTICA',
    implementation: '1 minuto setup',
  },
  {
    id: 58,
    category: 'EMERGENCIAS Y SOLUCIONES RÁPIDAS',
    tool: 'Guía Rápida para Manchas y Desastres Domésticos',
    description: 'Soluciones inmediatas para derrames y manchas',
    prompt: 'Mi hijo acaba de derramar [tipo de mancha] sobre [superficie]. ¿Cuál es el método más rápido y efectivo para limpiarlo con productos que probablemente tengo en casa?',
    timeSaved: 'Variable',
    urgency: 'ALTA',
    implementation: '30 segundos setup',
  },
  {
    id: 59,
    category: 'EMERGENCIAS Y SOLUCIONES RÁPIDAS',
    tool: 'Protocolo de Niño Enfermo en Casa',
    description: 'Qué hacer cuando tu hijo se enferma inesperadamente',
    prompt: 'Mi hijo de [edad] se despertó con [síntomas]. No puede ir al colegio. Crea un plan de acción para hoy: qué citas cancelar, cómo organizar mi trabajo, qué tener a mano para cuidarle y cuándo llamar al médico.',
    timeSaved: '1 hora/mañana',
    urgency: 'CRÍTICA',
    implementation: '2 minutos setup',
  },
  {
    id: 60,
    category: 'EMERGENCIAS Y SOLUCIONES RÁPIDAS',
    tool: 'Localizador de Objetos Perdidos',
    description: 'Una estrategia para encontrar llaves, móviles o el peluche favorito',
    prompt: 'No encuentro [objeto perdido] y lo necesito urgentemente. La última vez que lo recuerdo haber visto fue [contexto]. Guíame con una serie de preguntas lógicas para reconstruir mis pasos y encontrarlo.',
    timeSaved: '20 min/búsqueda',
    urgency: 'ALTA',
    implementation: '1 minuto setup',
  },

  // === DESARROLLO PROFESIONAL Y EMPRENDIMIENTO ===
  {
    id: 61,
    category: 'DESARROLLO PROFESIONAL Y EMPRENDIMIENTO',
    tool: 'Optimizador de CV para Madres',
    description: 'Adapta tu CV a roles flexibles o remotos',
    prompt: 'Soy madre, [X] años de experiencia en [campo], busco rol [flexible/remoto] como [puesto]. Mi último CV es: [pegar CV]. Adapta mi experiencia para destacar habilidades transferibles, minimizar brechas laborales y atraer a empresas pro-familia.',
    timeSaved: '4 horas/aplicación',
    urgency: 'MEDIA',
    implementation: '10 minutos setup',
  },
  {
    id: 62,
    category: 'DESARROLLO PROFESIONAL Y EMPRENDIMIENTO',
    tool: 'Preparador de Entrevistas (Roles Flexibles)',
    description: 'Simula entrevistas para roles pro-familia',
    prompt: 'Tengo entrevista para [puesto] en [empresa], descripción de puesto: [pegar]. Soy madre, mis prioridades son [flexibilidad, balance]. Simula la entrevista, hazme preguntas difíciles sobre mi brecha laboral y cómo gestionaré responsabilidades.',
    timeSaved: '3 horas/entrevista',
    urgency: 'ALTA',
    implementation: '5 minutos setup',
  },
  {
    id: 63,
    category: 'DESARROLLO PROFESIONAL Y EMPRENDIMIENTO',
    tool: 'Generador de Ideas de Negocio (Compatibles con Maternidad)',
    description: 'Encuentra negocios compatibles con la maternidad',
    prompt: 'Mis habilidades: [lista], pasiones: [lista], capital inicial: $[X], horas disponibles/semana: [X]. Genera 5 ideas de negocio que pueda empezar desde casa, con bajo riesgo y potencial de crecimiento mientras crío a mis hijos.',
    timeSaved: '10 horas/investigación',
    urgency: 'BAJA',
    implementation: '5 minutos setup',
  },
  {
    id: 64,
    category: 'DESARROLLO PROFESIONAL Y EMPRENDIMIENTO',
    tool: 'Asistente de Networking (Online y Presencial)',
    description: 'Crea mensajes para conectar profesionalmente',
    prompt: 'Quiero conectar en LinkedIn con [nombre], [puesto] en [empresa]. Nuestro punto en común es [X]. Soy madre volviendo al mundo laboral en [campo]. Escribe un mensaje corto y memorable para iniciar una conversación profesional.',
    timeSaved: '15 min/contacto',
    urgency: 'BAJA',
    implementation: '2 minutos setup',
  },
  {
    id: 65,
    category: 'DESARROLLO PROFESIONAL Y EMPRENDIMIENTO',
    tool: 'Plan de Aprendizaje Personalizado (Upskilling)',
    description: 'Diseña una ruta para adquirir nuevas habilidades',
    prompt: 'Quiero aprender [habilidad] para reincorporarme a [industria]. Tengo [X] horas/semana, presupuesto $[X], mi estilo de aprendizaje es [visual/práctico]. Crea un plan de 3 meses con recursos online (cursos, podcasts, libros).',
    timeSaved: '5 horas/planificación',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 66,
    category: 'DESARROLLO PROFESIONAL Y EMPRENDIMIENTO',
    tool: 'Optimizador de Perfil de LinkedIn',
    description: 'Mejora tu perfil para atraer reclutadores',
    prompt: 'Mi perfil de LinkedIn: [link]. Soy madre buscando reingresar a [campo]. Optimiza mi titular, resumen y experiencia para destacar mis fortalezas, justificar mi pausa profesional y usar palabras clave para [puestos deseados].',
    timeSaved: '2 horas',
    urgency: 'MEDIA',
    implementation: '10 minutos setup',
  },
  {
    id: 67,
    category: 'DESARROLLO PROFESIONAL Y EMPRENDIMIENTO',
    tool: 'Coach de Negociación Salarial (Considerando Flexibilidad)',
    description: 'Prepara tu argumentación para pedir lo que mereces',
    prompt: 'He recibido una oferta para [puesto] por $[salario]. Quiero negociar un [aumento del X%/más flexibilidad]. Ayúdame a estructurar mi contraoferta, justificando mi valor y presentando mis peticiones de forma profesional.',
    timeSaved: '3 horas/negociación',
    urgency: 'ALTA',
    implementation: '10 minutos setup',
  },
  {
    id: 68,
    category: 'DESARROLLO PROFESIONAL Y EMPRENDIMIENTO',
    tool: 'Generador de Contenido para Redes Sociales (Marca Personal)',
    description: 'Crea posts para posicionarte como experta',
    prompt: 'Quiero construir mi marca personal en [campo]. Mi audiencia son [descripción]. Genera 5 ideas de contenido para [LinkedIn/Instagram] que demuestren mi experiencia y pueda crear en menos de 30 minutos cada una.',
    timeSaved: '2 horas/semana',
    urgency: 'BAJA',
    implementation: '5 minutos setup',
  },
  {
    id: 69,
    category: 'DESARROLLO PROFESIONAL Y EMPRENDIMIENTO',
    tool: 'Asistente para Gestión del Tiempo (Side Hustle y Familia)',
    description: 'Organiza tu día para compatibilizarlo todo',
    prompt: 'Trabajo en mi [negocio/proyecto personal] y cuido de mis hijos. Mis bloques de tiempo disponibles son [lista]. Mis 3 tareas más importantes esta semana son [lista]. Ayúdame a organizar mi agenda diaria para ser productiva sin sacrificar tiempo familiar.',
    timeSaved: '1 hora/semana',
    urgency: 'ALTA',
    implementation: '5 minutos setup',
  },
  {
    id: 70,
    category: 'DESARROLLO PROFESIONAL Y EMPRENDIMIENTO',
    tool: 'Simulador de Elevator Pitch',
    description: 'Define y practica cómo presentarte profesionalmente',
    prompt: 'Soy [profesión] y ayudo a [audiencia] a [resolver problema]. Ayúdame a refinar esta frase para que sea un "elevator pitch" de 30 segundos, memorable e impactante, que pueda usar en eventos de networking.',
    timeSaved: '1 hora',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 71,
    category: 'DESARROLLO PROFESIONAL Y EMPRENDIMIENTO',
    tool: 'Buscador de Oportunidades de Trabajo Remoto/Flexible',
    description: 'Encuentra ofertas que se ajusten a tu vida',
    prompt: 'Busco un puesto de [profesión] con [X] años de experiencia. Mis requisitos no negociables son [trabajo remoto, horario flexible]. Dame 5 keywords y 3 bolsas de empleo especializadas para encontrar este tipo de ofertas.',
    timeSaved: '4 horas/búsqueda',
    urgency: 'MEDIA',
    implementation: '2 minutos setup',
  },
  {
    id: 72,
    category: 'DESARROLLO PROFESIONAL Y EMPRENDIMIENTO',
    tool: 'Redactor de Emails Profesionales Clave',
    description: 'Escribe emails para seguimiento, agradecimiento, etc.',
    prompt: 'Necesito escribir un email de [seguimiento tras una entrevista/agradecimiento a un contacto]. El contexto es [descripción]. Escribe un borrador profesional, conciso y que invite a una respuesta.',
    timeSaved: '15 min/email',
    urgency: 'MEDIA',
    implementation: '2 minutos setup',
  },

  // === FINANZAS PERSONALES Y FAMILIARES ===
  {
    id: 73,
    category: 'FINANZAS PERSONALES Y FAMILIARES',
    tool: 'Analista de Gastos "Hormiga"',
    description: 'Identifica y reduce pequeños gastos recurrentes',
    prompt: 'Mis categorías de gastos mensuales son: [lista con montos]. No sé a dónde se va el dinero. Analiza estos gastos, identifica 5 "gastos hormiga" y sugiere alternativas o recortes que ahorren al menos $[X] al mes sin afectar mi calidad de vida familiar.',
    timeSaved: '2 horas/mes',
    urgency: 'MEDIA',
    implementation: '10 minutos setup',
  },
  {
    id: 74,
    category: 'FINANZAS PERSONALES Y FAMILIARES',
    tool: 'Planificador de Ahorro para la Educación de los Hijos',
    description: 'Estrategias para el futuro educativo de tus hijos',
    prompt: 'Tengo [X] hijos de [edades]. Mi capacidad de ahorro mensual es $[X]. Quiero empezar a ahorrar para su educación universitaria. Compara opciones como [cuenta de ahorros, fondo de inversión, etc.] y sugiere la mejor estrategia para mi perfil de riesgo [conservador/moderado/agresivo].',
    timeSaved: '5 horas/investigación',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 75,
    category: 'FINANZAS PERSONALES Y FAMILIARES',
    tool: 'Negociador de Facturas y Suscripciones',
    description: 'Genera guiones para reducir gastos fijos',
    prompt: 'Mis suscripciones mensuales son: [lista con precios]. Mi factura de [servicio, ej: internet] es de $[X]. Genera un guion para llamar a [proveedor] y negociar una tarifa más baja, y ayúdame a decidir qué 3 suscripciones eliminar según su uso y costo-beneficio.',
    timeSaved: '1 hora/negociación',
    urgency: 'ALTA',
    implementation: '5 minutos setup',
  },
  {
    id: 76,
    category: 'FINANZAS PERSONALES Y FAMILIARES',
    tool: 'Asesor de Ingresos Extra (Side Hustles)',
    description: 'Ideas para generar ingresos en tu tiempo libre',
    prompt: 'Soy madre, mis habilidades son [lista], tengo [X] horas libres a la semana [especificar horarios]. Sugiere 3 formas realistas de generar ingresos extra desde casa, con un plan de acción para empezar cada una y una estimación de ingresos potenciales.',
    timeSaved: '8 horas/investigación',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 77,
    category: 'FINANZAS PERSONALES Y FAMILIARES',
    tool: 'Simulador de Metas Financieras (Casa, Viajes)',
    description: 'Visualiza cómo alcanzar tus objetivos económicos',
    prompt: 'Mi meta es [ej: dar el enganche de una casa] de $[X] en [Y] años. Mis ingresos son $[X] y mis ahorros actuales son $[X]. Crea un plan de ahorro mensual, sugiere ajustes en mi presupuesto y calcula si la meta es realista. De no serlo, ¿qué variables debo ajustar?',
    timeSaved: '3 horas/planificación',
    urgency: 'BAJA',
    implementation: '5 minutos setup',
  },
  {
    id: 78,
    category: 'FINANZAS PERSONALES Y FAMILIARES',
    tool: 'Educador Financiero para Niños',
    description: 'Crea lecciones de dinero para tus hijos',
    prompt: 'Quiero enseñar a mi hijo de [edad] sobre [concepto financiero, ej: el ahorro, el valor del dinero]. Su personaje favorito es [X]. Crea una historia corta o una actividad lúdica que le enseñe este concepto de forma divertida y fácil de entender.',
    timeSaved: '1 hora/lección',
    urgency: 'BAJA',
    implementation: '2 minutos setup',
  },
  {
    id: 79,
    category: 'FINANZAS PERSONALES Y FAMILIARES',
    tool: 'Optimizador de Puntos y Recompensas',
    description: 'Saca el máximo provecho a tus tarjetas de crédito',
    prompt: 'Tengo las siguientes tarjetas de crédito: [lista con sus programas de puntos/cashback]. Mis principales categorías de gasto son [supermercado, gasolina, etc.]. ¿Cuál tarjeta debo usar para cada categoría para maximizar mis recompensas?',
    timeSaved: '1 hora/mes',
    urgency: 'BAJA',
    implementation: '10 minutos setup',
  },
  {
    id: 80,
    category: 'FINANZAS PERSONALES Y FAMILIARES',
    tool: 'Planificador de Compras Grandes',
    description: 'Investiga y decide antes de una gran compra',
    prompt: 'Necesito comprar un [electrodoméstico/coche]. Mi presupuesto es $[X]. Mis prioridades son [eficiencia energética, seguridad, tamaño]. Compara las 3 mejores opciones del mercado, resumiendo pros, contras y precio aproximado.',
    timeSaved: '6 horas/investigación',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 81,
    category: 'FINANZAS PERSONALES Y FAMILIARES',
    tool: 'Analista de Pólizas de Seguros',
    description: 'Entiende si tienes la cobertura que necesitas',
    prompt: 'Tengo seguros de [vida/coche/hogar]. No entiendo bien las coberturas. Explícame en términos sencillos los 3 puntos más importantes de mi póliza de [tipo] y si hay alguna laguna de cobertura obvia para una familia como la mía.',
    timeSaved: '2 horas/póliza',
    urgency: 'MEDIA',
    implementation: '10 minutos setup',
  },
  {
    id: 82,
    category: 'FINANZAS PERSONALES Y FAMILIARES',
    tool: 'Estratega para Reducción de Deudas',
    description: 'Crea un plan para salir de deudas más rápido',
    prompt: 'Mis deudas son: [lista con monto, interés y pago mínimo]. Mis ingresos para pagar deudas son $[X] al mes. Compara los métodos "Bola de Nieve" y "Avalancha" y dime cuál me conviene más y por qué. Crea el plan de pagos.',
    timeSaved: '4 horas/planificación',
    urgency: 'ALTA',
    implementation: '15 minutos setup',
  },
  {
    id: 83,
    category: 'FINANZAS PERSONALES Y FAMILIARES',
    tool: 'Comparador de Servicios Financieros',
    description: 'Elige la mejor cuenta bancaria o hipoteca',
    prompt: 'Estoy buscando [una cuenta de ahorros para niños/una hipoteca]. Mis prioridades son [bajas comisiones, alta rentabilidad, buen servicio al cliente]. ¿Cuáles son los 3 factores clave que debo comparar entre diferentes bancos?',
    timeSaved: '3 horas/investigación',
    urgency: 'MEDIA',
    implementation: '2 minutos setup',
  },
  {
    id: 84,
    category: 'FINANZAS PERSONALES Y FAMILIARES',
    tool: 'Planificador de Jubilación para Madres',
    description: 'Asegura tu futuro considerando pausas laborales',
    prompt: 'Tengo [edad] y [X] ahorrado para la jubilación. Estuve [X] años sin cotizar por la crianza. Mi capacidad de ahorro es $[X] al mes. ¿Qué estrategias puedo usar para acelerar mi ahorro y compensar el tiempo perdido?',
    timeSaved: '5 horas/investigación',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },

  // === RELACIONES Y COMUNICACIÓN ===
  {
    id: 85,
    category: 'RELACIONES Y COMUNICACIÓN',
    tool: 'Coach de Comunicación con la Pareja',
    description: 'Mejora el diálogo sobre temas difíciles',
    prompt: 'Quiero hablar con mi pareja sobre [tema sensible] pero siempre terminamos discutiendo. Mi perspectiva es [descripción]. Suelo reaccionar [forma]. Dame una forma de iniciar la conversación usando "mensajes yo" y enfocada en soluciones.',
    timeSaved: '1 hora/conversación',
    urgency: 'ALTA',
    implementation: '5 minutos setup',
  },
  {
    id: 86,
    category: 'RELACIONES Y COMUNICACIÓN',
    tool: 'Planificador de Citas Románticas (en casa o fuera)',
    description: 'Ideas para reavivar la conexión en pareja',
    prompt: 'Necesitamos una cita con mi pareja. Presupuesto $[X], tiempo disponible [X horas], energía [baja/alta]. Sugiere 3 ideas: una en casa después de que los niños duerman, una de día y una de noche.',
    timeSaved: '1 hora/cita',
    urgency: 'MEDIA',
    implementation: '3 minutos setup',
  },
  {
    id: 87,
    category: 'RELACIONES Y COMUNICACIÓN',
    tool: 'Mediador de Conflictos Familiares (con familia extendida)',
    description: 'Navega situaciones tensas con suegros, cuñados, etc.',
    prompt: 'Tengo un conflicto con [mi suegra] sobre [tema]. Su postura es [descripción] y me hace sentir [emoción]. Necesito un guion para abordar el tema con respeto pero estableciendo un límite claro.',
    timeSaved: 'Variable',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 88,
    category: 'RELACIONES Y COMUNICACIÓN',
    tool: 'Fortalecedor de Amistades (Mantener el contacto)',
    description: 'Pequeños gestos para cuidar a tus amigas',
    prompt: 'Echo de menos a mis amigas pero no tengo tiempo para largas llamadas. Sugiere 5 formas rápidas (menos de 5 min) y significativas de mantener el contacto y demostrar que me importan durante la semana.',
    timeSaved: 'Variable',
    urgency: 'BAJA',
    implementation: '2 minutos setup',
  },
  {
    id: 89,
    category: 'RELACIONES Y COMUNICACIÓN',
    tool: 'Guía para Conversaciones sobre Crianza en Pareja',
    description: 'Alinea vuestros estilos y decisiones de crianza',
    prompt: 'Mi pareja y yo no estamos de acuerdo sobre [tema de crianza, ej: disciplina, alimentación]. Su enfoque es [descripción] y el mío es [descripción]. Crea una agenda con 3 puntos para una conversación constructiva sobre el tema.',
    timeSaved: '2 horas/discusión',
    urgency: 'ALTA',
    implementation: '5 minutos setup',
  },
  {
    id: 90,
    category: 'RELACIONES Y COMUNICACIÓN',
    tool: 'Generador de Mensajes de Agradecimiento y Afecto',
    description: 'Expresa gratitud a tu red de apoyo',
    prompt: 'Quiero agradecer a [mi pareja/mi madre/una amiga] por [ayuda específica]. Escribe un mensaje de texto corto pero sincero que exprese mi gratitud y lo mucho que valoro su apoyo.',
    timeSaved: '10 min/mensaje',
    urgency: 'BAJA',
    implementation: '1 minuto setup',
  },
  {
    id: 91,
    category: 'RELACIONES Y COMUNICACIÓN',
    tool: 'Asistente para Mantener el Contacto con Familia Lejana',
    description: 'Crea un sistema para no perder la conexión',
    prompt: 'Quiero que mis hijos tengan relación con [los abuelos/primos] que viven lejos. Sugiere una rutina mensual simple que incluya [videollamadas, envío de dibujos, etc.] para mantener el vínculo fuerte.',
    timeSaved: '30 min/mes',
    urgency: 'BAJA',
    implementation: '5 minutos setup',
  },
  {
    id: 92,
    category: 'RELACIONES Y COMUNICACIÓN',
    tool: 'Traductor de "Mamá-lenguaje" a "Pareja-lenguaje"',
    description: 'Comunica tus necesidades de forma que tu pareja entienda',
    prompt: 'Cuando digo "Estoy agotada", lo que realmente necesito es [descripción específica de ayuda]. Traduce 3 frases comunes de "mamá-lenguaje" a peticiones claras y directas que mi pareja pueda entender y sobre las que pueda actuar.',
    timeSaved: 'Variable',
    urgency: 'ALTA',
    implementation: '3 minutos setup',
  },
  {
    id: 93,
    category: 'RELACIONES Y COMUNICACIÓN',
    tool: 'Creador de Tradiciones Familiares',
    description: 'Genera ideas para crear recuerdos duraderos',
    prompt: 'Quiero empezar una nueva tradición familiar para [cumpleaños/inicio del curso escolar/domingos]. Somos una familia con hijos de [edades] y nuestros valores son [ej: creatividad, naturaleza]. Sugiere 3 ideas de tradiciones sencillas y significativas.',
    timeSaved: '1 hora/idea',
    urgency: 'BAJA',
    implementation: '2 minutos setup',
  },
  {
    id: 94,
    category: 'RELACIONES Y COMUNICACIÓN',
    tool: 'Gestor de Expectativas (con pareja y familia)',
    description: 'Aclara roles y responsabilidades para evitar resentimiento',
    prompt: 'Siento que la carga de [gestión del hogar/planificación] recae sobre mí. Quiero hablar con mi pareja para repartir responsabilidades de forma más equitativa. Ayúdame a listar todas las tareas de carga mental y a proponer un sistema de reparto.',
    timeSaved: '3 horas/conversación',
    urgency: 'ALTA',
    implementation: '10 minutos setup',
  },
  {
    id: 95,
    category: 'RELACIONES Y COMUNICACIÓN',
    tool: 'Facilitador de Reuniones Familiares Productivas',
    description: 'Organiza "consejos de familia" para tomar decisiones juntos',
    prompt: 'Queremos hacer una reunión familiar semanal para planificar y resolver problemas. Hijos de [edades]. Crea una estructura de 15 minutos para estas reuniones que sea divertida y permita que todos participen.',
    timeSaved: '30 min/semana',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 96,
    category: 'RELACIONES Y COMUNICACIÓN',
    tool: 'Consejero para la Relación con los Suegros',
    description: 'Encuentra el equilibrio en la relación con la familia política',
    prompt: 'Mis suegros [hacen un comentario/tienen una actitud] que me incomoda. Quiero mantener una buena relación por mi pareja y mis hijos. ¿Cómo puedo gestionar esta situación específica con diplomacia?',
    timeSaved: 'Variable',
    urgency: 'MEDIA',
    implementation: '3 minutos setup',
  },

  // === SALUD Y NUTRICIÓN ===
  {
    id: 97,
    category: 'SALUD Y NUTRICIÓN',
    tool: 'Nutricionista Pediátrico AI (para niños "picky eaters")',
    description: 'Ideas creativas para niños que comen poco o mal',
    prompt: 'Mi hijo de [edad] se niega a comer [verduras/proteínas]. Sus alimentos favoritos son [lista]. Dame 5 estrategias creativas y recetas para introducir [alimento rechazado] en su dieta de forma divertida y sin presionar.',
    timeSaved: '2 horas/semana',
    urgency: 'ALTA',
    implementation: '5 minutos setup',
  },
  {
    id: 98,
    category: 'SALUD Y NUTRICIÓN',
    tool: 'Planificador de Snacks Saludables y Rápidos',
    description: 'Opciones nutritivas para llevar o para media tarde',
    prompt: 'Necesito ideas de snacks saludables para mis hijos de [edades] que pueda preparar en menos de 5 minutos. Dame una lista de 10 opciones que incluyan carbohidratos, proteína y grasa saludable.',
    timeSaved: '1 hora/semana',
    urgency: 'MEDIA',
    implementation: '3 minutos setup',
  },
  {
    id: 99,
    category: 'SALUD Y NUTRICIÓN',
    tool: 'Adaptador de Recetas para Alergias e Intolerancias',
    description: 'Modifica tus platos favoritos para que sean seguros',
    prompt: 'Quiero hacer [receta], pero mi hijo tiene alergia a [ingrediente]. Sugiere 3 sustituciones seguras y efectivas para ese ingrediente y ajusta la receta si es necesario.',
    timeSaved: '20 min/receta',
    urgency: 'ALTA',
    implementation: '2 minutos setup',
  },
  {
    id: 100,
    category: 'SALUD Y NUTRICIÓN',
    tool: 'Coach de Hidratación Familiar',
    description: 'Asegura que todos en la familia beban suficiente agua',
    prompt: 'Me cuesta que mis hijos y yo bebamos suficiente agua durante el día. Sugiere 5 trucos divertidos y un sistema visual para fomentar la hidratación en toda la familia.',
    timeSaved: 'Variable',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 101,
    category: 'SALUD Y NUTRICIÓN',
    tool: 'Generador de Ideas para Lunchbox Escolares',
    description: 'Crea almuerzos variados y apetecibles para el colegio',
    prompt: 'Estoy aburrida de preparar siempre lo mismo para el lunchbox de mi hijo de [edad]. Dame 5 ideas de almuerzos escolares equilibrados, fáciles de comer y que se conserven bien sin refrigeración, usando el método de los 5 compartimentos.',
    timeSaved: '1.5 horas/semana',
    urgency: 'MEDIA',
    implementation: '3 minutos setup',
  },
  {
    id: 102,
    category: 'SALUD Y NUTRICIÓN',
    tool: 'Planificador de Actividad Física en Familia',
    description: 'Ideas para moverse juntos y divertirse',
    prompt: 'Queremos ser una familia más activa. Tenemos [X] tiempo los fines de semana. Hijos de [edades]. Sugiere 3 actividades físicas que podamos hacer todos juntos, que sean económicas y se adapten a diferentes niveles de energía.',
    timeSaved: '45 min/semana',
    urgency: 'BAJA',
    implementation: '2 minutos setup',
  },
  {
    id: 103,
    category: 'SALUD Y NUTRICIÓN',
    tool: 'Asistente de Salud Mental Postparto',
    description: 'Identifica síntomas y busca recursos de apoyo',
    prompt: 'Estoy en el postparto y me siento [describir emociones]. No sé si es normal. Ayúdame a diferenciar entre "baby blues" y una posible depresión postparto, y dame 3 recursos fiables a los que puedo acudir en [país/ciudad].',
    timeSaved: 'Variable',
    urgency: 'CRÍTICA',
    implementation: '3 minutos setup',
  },
  {
    id: 104,
    category: 'SALUD Y NUTRICIÓN',
    tool: 'Guía de Suplementos para Madres',
    description: 'Entiende qué vitaminas y minerales podrías necesitar',
    prompt: 'Como madre lactante/ocupada, siento que me falta energía. Basado en una dieta estándar, ¿cuáles son los 3 suplementos más recomendados para mujeres en mi situación y por qué? (Aviso: consulta siempre a un médico)',
    timeSaved: '2 horas/investigación',
    urgency: 'BAJA',
    implementation: '2 minutos setup',
  },
  {
    id: 105,
    category: 'SALUD Y NUTRICIÓN',
    tool: 'Intérprete de Etiquetas Nutricionales',
    description: 'Toma decisiones de compra más saludables en el súper',
    prompt: 'Estoy en el supermercado comparando dos tipos de [yogur/cereales]. Pego las dos etiquetas nutricionales aquí: [pegar info]. ¿Cuál es la opción más saludable para mis hijos y por qué? Explícamelo en 3 puntos clave.',
    timeSaved: '5 min/producto',
    urgency: 'MEDIA',
    implementation: '1 minuto setup',
  },
  {
    id: 106,
    category: 'SALUD Y NUTRICIÓN',
    tool: 'Motivador de Hábitos Saludables',
    description: 'Encuentra la motivación para cuidarte',
    prompt: 'Quiero empezar a [hacer ejercicio/comer mejor], pero me falta motivación. Mi mayor obstáculo es [el cansancio/la falta de tiempo]. Dame 3 estrategias de mentalidad y un primer paso muy pequeño que pueda dar hoy mismo.',
    timeSaved: 'Variable',
    urgency: 'MEDIA',
    implementation: '2 minutos setup',
  },
  {
    id: 107,
    category: 'SALUD Y NUTRICIÓN',
    tool: 'Planificador de "Meal Prep" para la Semana',
    description: 'Cocina una vez, come saludable toda la semana',
    prompt: 'Tengo 2 horas el domingo para preparar comidas. Quiero adelantar 3 cenas y los desayunos de la semana para una familia de [X]. Dame un plan de "meal prep" eficiente, con recetas que se conserven bien y una lista de tareas paso a paso.',
    timeSaved: '5 horas/semana',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 108,
    category: 'SALUD Y NUTRICIÓN',
    tool: 'Consejero de Sueño Infantil y Adulto',
    description: 'Mejora las rutinas de sueño de toda la familia',
    prompt: 'Mi hijo de [edad] está teniendo problemas para [dormirse/despertarse por la noche]. Su rutina actual es [descripción]. Analiza la rutina y sugiere 3 cambios específicos para mejorar su higiene del sueño. Además, dame un consejo para mi propio sueño.',
    timeSaved: 'Variable',
    urgency: 'ALTA',
    implementation: '3 minutos setup',
  },

  // === CREATIVIDAD Y OCIO ===
  {
    id: 109,
    category: 'CREATIVIDAD Y OCIO',
    tool: 'Generador de Proyectos de Arte con Niños',
    description: 'Ideas de manualidades con materiales caseros',
    prompt: 'Tengo a mi hijo de [edad] en casa y está aburrido. Los materiales que tengo son [lista de 5-10 cosas, ej: rollos de papel, pintura, pegamento]. Dame 3 ideas de manualidades que podamos hacer ahora mismo, con instrucciones paso a paso.',
    timeSaved: '30 min/actividad',
    urgency: 'MEDIA',
    implementation: '2 minutos setup',
  },
  {
    id: 110,
    category: 'CREATIVIDAD Y OCIO',
    tool: 'Planificador de Noches de Película Temáticas',
    description: 'Convierte ver una peli en una experiencia memorable',
    prompt: 'Queremos ver la película [nombre de la película] en familia. Sugiere un tema para la noche y danos 3 ideas sencillas para la cena/snacks, la decoración y una actividad relacionada para hacer antes o después de la película.',
    timeSaved: '1 hora/evento',
    urgency: 'BAJA',
    implementation: '3 minutos setup',
  },
  {
    id: 111,
    category: 'CREATIVIDAD Y OCIO',
    tool: 'DJ Personalizado para Playlists Familiares',
    description: 'Crea la banda sonora para diferentes momentos del día',
    prompt: 'Crea una playlist de 10 canciones para [la hora del desayuno/un viaje en coche/una tarde de juegos]. La música debe ser animada, apta para niños de [edades] pero que también nos guste a los adultos.',
    timeSaved: '20 min/playlist',
    urgency: 'BAJA',
    implementation: '1 minuto setup',
  },
  {
    id: 112,
    category: 'CREATIVIDAD Y OCIO',
    tool: 'Guía de Jardinería para Principiantes (con niños)',
    description: 'Inicia un pequeño huerto en casa',
    prompt: 'Tenemos un [balcón/pequeño jardín] con [mucho/poco] sol. Queremos empezar un pequeño huerto con nuestros hijos. Sugiere 3 plantas (hortalizas o aromáticas) que sean fáciles de cuidar para principiantes y que a los niños les guste ver crecer.',
    timeSaved: '3 horas/investigación',
    urgency: 'BAJA',
    implementation: '3 minutos setup',
  },
  {
    id: 113,
    category: 'CREATIVIDAD Y OCIO',
    tool: 'Storyteller para Cuentos de Buenas Noches',
    description: 'Inventa historias sobre la marcha',
    prompt: 'Es la hora de dormir y mi hijo me pide un cuento. Dame 3 elementos para empezar una historia improvisada: un personaje principal, un lugar mágico y un problema inesperado. A partir de ahí, yo sigo.',
    timeSaved: '10 min/noche',
    urgency: 'MEDIA',
    implementation: '30 segundos setup',
  },
  {
    id: 114,
    category: 'CREATIVIDAD Y OCIO',
    tool: 'Organizador de Club de Lectura Familiar',
    description: 'Fomenta el amor por la lectura en casa',
    prompt: 'Quiero empezar un club de lectura con mis hijos de [edades]. Sugiere un primer libro que podamos leer todos (o en versiones adaptadas) y 3 preguntas divertidas para iniciar la conversación sobre la historia.',
    timeSaved: '2 horas/investigación',
    urgency: 'BAJA',
    implementation: '3 minutos setup',
  },
  {
    id: 115,
    category: 'CREATIVIDAD Y OCIO',
    tool: 'Planificador de Aventuras Locales (Explorar la ciudad)',
    description: 'Descubre joyas ocultas en tu propia ciudad',
    prompt: 'Vivimos en [ciudad] y queremos hacer algo diferente este fin de semana. Somos una familia con [intereses] y presupuesto [bajo]. Sugiere 3 "micro-aventuras" o lugares poco conocidos que podamos explorar en nuestra ciudad.',
    timeSaved: '1.5 horas/planificación',
    urgency: 'BAJA',
    implementation: '2 minutos setup',
  },
  {
    id: 116,
    category: 'CREATIVIDAD Y OCIO',
    tool: 'Instructor de Cocina en Familia (Recetas divertidas)',
    description: 'Cocinar juntos puede ser una fiesta',
    prompt: 'Quiero cocinar con mi hijo de [edad] este fin de semana. Dame una receta sencilla y divertida (ej: pizza casera, galletas decoradas) y asigna tareas específicas y seguras para él/ella durante el proceso.',
    timeSaved: '45 min/planificación',
    urgency: 'BAJA',
    implementation: '2 minutos setup',
  },
  {
    id: 117,
    category: 'CREATIVIDAD Y OCIO',
    tool: 'Creador de Búsquedas del Tesoro Personalizadas',
    description: 'Una actividad divertida para una tarde en casa o en el parque',
    prompt: 'Crea una búsqueda del tesoro de 5 pistas para mi hijo de [edad]. El escenario es [nuestra casa/el jardín]. Las pistas deben ser [adivinanzas/dibujos] y el tesoro final será [un snack/un libro].',
    timeSaved: '30 min/actividad',
    urgency: 'MEDIA',
    implementation: '3 minutos setup',
  },
  {
    id: 118,
    category: 'CREATIVIDAD Y OCIO',
    tool: 'Descubridor de Hobbies para Mamás',
    description: 'Encuentra una pasión más allá de la maternidad',
    prompt: 'Quiero encontrar un hobby para mí, pero no sé por dónde empezar. Mis intereses son [lista], tengo [X] horas a la semana y un presupuesto de $[X]. Sugiere 3 hobbies que podría probar y cómo dar el primer paso en cada uno.',
    timeSaved: '5 horas/investigación',
    urgency: 'MEDIA',
    implementation: '3 minutos setup',
  },
  {
    id: 119,
    category: 'CREATIVIDAD Y OCIO',
    tool: 'Generador de Proyectos DIY para el Hogar',
    description: 'Pequeños proyectos para mejorar tu casa en familia',
    prompt: 'Quiero hacer un proyecto DIY sencillo para [decorar la habitación de los niños/organizar la entrada]. Mi nivel de habilidad es [principiante]. Sugiere un proyecto que podamos hacer en un fin de semana y lista los materiales necesarios.',
    timeSaved: '4 horas/investigación',
    urgency: 'BAJA',
    implementation: '3 minutos setup',
  },
  {
    id: 120,
    category: 'CREATIVIDAD Y OCIO',
    tool: 'Planificador de Días de "No Hacer Nada"',
    description: 'Diseña un día de descanso y juego libre',
    prompt: 'Necesitamos un día de descanso total, sin planes ni obligaciones. Crea un "menú de opciones" de actividades relajadas que podamos hacer en casa (ej: construir un fuerte, leer juntos, maratón de pelis) para un día de pijama perfecto.',
    timeSaved: 'Variable',
    urgency: 'MEDIA',
    implementation: '2 minutos setup',
  },
];
