import type { Prompt } from '../types';

export const prompts: Prompt[] = [
  {
    id: 1,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Menú Semanal Automático',
    description: 'Planificador inteligente de comidas familiares',
    prompt: 'Soy madre de [X] hijos de [edades], presupuesto semanal $[cantidad], tiempo de cocina máximo [X] minutos, alimentos que NO comen: [lista]. Crea menú 7 días nutritivo + lista compras por secciones del supermercado.',
    timeSaved: '3 horas/semana',
    urgency: 'ALTA',
    implementation: '5 minutos setup',
  },
  {
    id: 2,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Lista Compras Inteligente',
    description: 'Generador automático optimizado por rutas',
    prompt: 'Necesito lista de compras para familia de [X], presupuesto $[X], supermercado [nombre], priorizar: productos frescos, evitar: [alergias]. Organiza por pasillos y sugiere alternativas económicas.',
    timeSaved: '45 min/compra',
    urgency: 'ALTA',
    implementation: '3 minutos setup',
  },
  {
    id: 3,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Rutina Matutina Familiar',
    description: 'Optimizador de mañanas sin estrés',
    prompt: 'Familia: [composición], horarios salida: [hora], tiempo disponible: [X] min. Diseña rutina matutina realista que incluya: desayuno, preparación niños, tiempo personal. Considera días escolares vs fines de semana.',
    timeSaved: '1 hora/mañana',
    urgency: 'ALTA',
    implementation: '10 minutos setup',
  },
  {
    id: 4,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Calendario Actividades Infantiles',
    description: 'Planificador de entretenimiento por edades',
    prompt: 'Niños de [edades], tiempo disponible [X] minutos, ubicación: [casa/exterior], materiales: [básicos], objetivo: [desarrollo/entretenimiento]. Sugiere 5 actividades apropiadas con instrucciones paso a paso.',
    timeSaved: '30 min/día',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 5,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Presupuesto Familiar Automático',
    description: 'Controlador de gastos inteligente',
    prompt: 'Ingresos mensuales: $[X], gastos fijos: [lista], número hijos: [X], objetivos ahorro: [X]. Crea presupuesto realista con alertas automáticas y sugerencias de optimización.',
    timeSaved: '2 horas/mes',
    urgency: 'ALTA',
    implementation: '15 minutos setup',
  },
  {
    id: 6,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Organizador de Citas Médicas',
    description: 'Gestor de salud familiar',
    prompt: 'Familia de [X] miembros, edades: [X], médicos frecuentes: [pediatra, dentista, etc.], recordatorios necesarios: [vacunas, controles]. Crea sistema de seguimiento y recordatorios automáticos.',
    timeSaved: '1 hora/mes',
    urgency: 'MEDIA',
    implementation: '10 minutos setup',
  },
  {
    id: 7,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Planificador Fin de Semana',
    description: 'Optimizador de tiempo familiar',
    prompt: 'Fin de semana disponible: [sábado/domingo], presupuesto: $[X], edades niños: [X], intereses familia: [lista]. Sugiere plan equilibrado: diversión + descanso + tareas necesarias.',
    timeSaved: '45 min/semana',
    urgency: 'BAJA',
    implementation: '5 minutos setup',
  },
  {
    id: 8,
    category: 'PLANIFICACIÓN FAMILIAR',
    tool: 'Preparación Vacaciones Familiares',
    description: 'Organizador de viajes sin estrés',
    prompt: 'Destino: [X], duración: [X] días, edades: [X], presupuesto: [X]. Crea checklist completo: documentos, equipaje por edad, actividades, emergencias, itinerario flexible.',
    timeSaved: '3 horas/viaje',
    urgency: 'BAJA',
    implementation: '20 minutos setup',
  },
  {
    id: 9,
    category: 'CRIANZA',
    tool: 'Resolvedor de Conflictos',
    description: 'IA para mediar peleas entre hermanos',
    prompt: 'Situación: [descripción conflicto], edades involucradas: [X], personalidades: [descripción]. Necesito 3 estrategias inmediatas para resolver sin gritos, explicando por qué funcionarán con estos niños específicos.',
    timeSaved: '45 min/día',
    urgency: 'ALTA',
    implementation: '2 minutos setup',
  },
  {
    id: 10,
    category: 'CRIANZA',
    tool: 'Generador de Consecuencias Lógicas',
    description: 'Sistema disciplinario respetuoso',
    prompt: 'Mi hijo de [edad] hizo [comportamiento], contexto: [situación]. Sugiere consecuencia lógica que enseñe sin castigar, apropiada para su desarrollo y que fortalezca nuestra relación.',
    timeSaved: '30 min/episodio',
    urgency: 'ALTA',
    implementation: '3 minutos setup',
  },
  {
    id: 11,
    category: 'CRIANZA',
    tool: 'Apoyo Tareas Escolares',
    description: 'Asistente educativo personalizado',
    prompt: 'Materia: [X], grado: [X], dificultad específica: [X], estilo aprendizaje del niño: [visual/auditivo/kinestésico]. Explica concepto de manera simple y sugiere actividad práctica para reforzar.',
    timeSaved: '1 hora/día',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 12,
    category: 'CRIANZA',
    tool: 'Detector de Necesidades Emocionales',
    description: 'Intérprete de comportamientos',
    prompt: 'Mi hijo de [edad] está mostrando: [comportamientos observados], cambios recientes: [contexto]. Ayúdame a entender qué necesidad emocional no está cubierta y cómo responder empáticamente.',
    timeSaved: '20 min/episodio',
    urgency: 'ALTA',
    implementation: '2 minutos setup',
  },
  {
    id: 13,
    category: 'CRIANZA',
    tool: 'Planificador de Tiempo de Calidad',
    description: 'Optimizador de conexión familiar',
    prompt: 'Tiempo disponible: [X] minutos, edad del niño: [X], su interés actual: [X], mi energía: [nivel 1-10]. Sugiere actividad específica que fortalezca nuestro vínculo y sea significativa para ambos.',
    timeSaved: 'Variable',
    urgency: 'MEDIA',
    implementation: '3 minutos setup',
  },
  {
    id: 14,
    category: 'CRIANZA',
    tool: 'Traductor de Rabietas',
    description: 'Decodificador emocional infantil',
    prompt: 'Edad: [X], situación de la rabieta: [contexto], intensidad: [1-10], duración: [tiempo]. Explica qué está comunicando realmente y dame estrategia específica para acompañar sin ceder ni controlar.',
    timeSaved: '30 min/episodio',
    urgency: 'ALTA',
    implementation: '2 minutos setup',
  },
  {
    id: 15,
    category: 'CRIANZA',
    tool: 'Fomentador de Independencia',
    description: 'Guía de autonomía por edades',
    prompt: 'Edad: [X], habilidad a desarrollar: [X], nivel actual del niño: [descripción]. Crea plan gradual de 2 semanas para que desarrolle esta habilidad sin frustración, con pasos específicos diarios.',
    timeSaved: 'Variable',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 16,
    category: 'CRIANZA',
    tool: 'Comunicador Efectivo',
    description: 'Traductor de lenguaje infantil',
    prompt: 'Necesito hablar con mi hijo de [edad] sobre: [tema difícil], su personalidad: [descripción]. Dame guión adaptado a su comprensión que sea honesto, apropiado y que invite al diálogo.',
    timeSaved: '15 min/conversación',
    urgency: 'ALTA',
    implementation: '3 minutos setup',
  },
  {
    id: 17,
    category: 'HOGAR',
    tool: 'Sistema de Limpieza Inteligente',
    description: 'Optimizador de tareas domésticas',
    prompt: 'Casa de [X] habitaciones, [X] habitantes, mascotas: [sí/no], tiempo disponible: [X] horas/semana. Crea rutina de limpieza realista dividida por días, priorizando áreas críticas y optimizando esfuerzo.',
    timeSaved: '5 horas/semana',
    urgency: 'ALTA',
    implementation: '10 minutos setup',
  },
  {
    id: 18,
    category: 'HOGAR',
    tool: 'Organizador de Espacios',
    description: 'Consultor de orden y funcionalidad',
    prompt: 'Espacio a organizar: [habitación], problema principal: [descripción], presupuesto: $[X], niños que usan el espacio: [edades]. Diseña sistema de organización que sea fácil de mantener por toda la familia.',
    timeSaved: '2 horas/espacio',
    urgency: 'MEDIA',
    implementation: '15 minutos setup',
  },
  {
    id: 19,
    category: 'HOGAR',
    tool: 'Planificador de Mantenimiento',
    description: 'Calendario preventivo del hogar',
    prompt: 'Tipo de vivienda: [casa/apto], antigüedad: [años], electrodomésticos: [lista], última revisión: [cuándo]. Crea cronograma anual de mantenimiento con recordatorios mensuales y presupuesto estimado.',
    timeSaved: '3 horas/año',
    urgency: 'BAJA',
    implementation: '20 minutos setup',
  },
  {
    id: 20,
    category: 'HOGAR',
    tool: 'Optimizador de Lavandería',
    description: 'Automatizador de ropa familiar',
    prompt: 'Familia de [X] personas, frecuencia lavado: [X] veces/semana, tipo de ropa predominante: [casual/formal/mixta]. Crea sistema eficiente: clasificación, horarios, doblado y guardado que funcione para todos.',
    timeSaved: '3 horas/semana',
    urgency: 'ALTA',
    implementation: '5 minutos setup',
  },
  {
    id: 21,
    category: 'HOGAR',
    tool: 'Controlador de Inventarios',
    description: 'Gestor de despensa y suministros',
    prompt: 'Tamaño familia: [X], espacio almacenamiento: [descripción], presupuesto mensual: $[X]. Crea sistema de control de stock con alertas automáticas y lista de compras inteligente.',
    timeSaved: '1 hora/mes',
    urgency: 'MEDIA',
    implementation: '15 minutos setup',
  },
  {
    id: 22,
    category: 'HOGAR',
    tool: 'Coordinador Familiar',
    description: 'Sincronizador de horarios y actividades',
    prompt: 'Miembros familia: [X], actividades regulares: [lista], vehículos disponibles: [X]. Optimiza logística familiar, detecta conflictos de horarios y sugiere soluciones de transporte.',
    timeSaved: '2 horas/semana',
    urgency: 'ALTA',
    implementation: '10 minutos setup',
  },
  {
    id: 23,
    category: 'AUTOCUIDADO',
    tool: 'Detector de Agotamiento',
    description: 'Monitor de señales de burnout maternal',
    prompt: 'Síntomas que siento: [lista], duración: [tiempo], cambios en mi comportamiento: [descripción], apoyo disponible: [nivel]. Analiza mi estado, identifica riesgo de burnout y sugiere plan de acción inmediato.',
    timeSaved: '2 horas/día',
    urgency: 'ALTA',
    implementation: '3 minutos setup',
  },
  {
    id: 24,
    category: 'AUTOCUIDADO',
    tool: 'Planificador de Tiempo Personal',
    description: 'Optimizador de momentos para mamá',
    prompt: 'Tiempo real disponible: [X] minutos, energía actual: [1-10], necesidad emocional: [relajación/activación/conexión]. Sugiere actividad específica de autocuidado que sea realista y realmente efectiva para mi estado actual.',
    timeSaved: 'Variable',
    urgency: 'ALTA',
    implementation: '2 minutos setup',
  },
  {
    id: 25,
    category: 'AUTOCUIDADO',
    tool: 'Gestor de Límites Saludables',
    description: 'Asistente para decir NO sin culpa',
    prompt: 'Situación: [descripción petición], mi capacidad actual: [%], consecuencias de aceptar: [lista], relación con quien pide: [tipo]. Ayúdame a evaluar y dame script respetuoso para responder.',
    timeSaved: '30 min/decisión',
    urgency: 'ALTA',
    implementation: '2 minutos setup',
  },
  {
    id: 26,
    category: 'AUTOCUIDADO',
    tool: 'Optimizador de Energía Maternal',
    description: 'Administrador de recursos personales',
    prompt: 'Hora del día: [X], nivel energía: [1-10], tareas pendientes: [lista], tiempo hasta siguiente break: [X] min. Prioriza tareas según mi energía y sugiere micro-descansos estratégicos.',
    timeSaved: '1 hora/día',
    urgency: 'MEDIA',
    implementation: '3 minutos setup',
  },
  {
    id: 27,
    category: 'AUTOCUIDADO',
    tool: 'Consejero de Redes de Apoyo',
    description: 'Activador de ayuda externa',
    prompt: 'Situación actual: [descripción estrés], personas disponibles: [lista], tipo de ayuda que necesito: [específica]. Identifica mejor opción de apoyo y dame script para pedir ayuda sin sentirme culpable.',
    timeSaved: '45 min/crisis',
    urgency: 'ALTA',
    implementation: '5 minutos setup',
  },
  {
    id: 28,
    category: 'AUTOCUIDADO',
    tool: 'Tracker de Bienestar Integral',
    description: 'Monitor holístico de salud maternal',
    prompt: 'Sueño: [horas/calidad], alimentación: [descripción], ejercicio: [frecuencia], conexiones sociales: [nivel], tiempo personal: [cantidad]. Evalúa mi bienestar integral y sugiere 1 cambio específico prioritario.',
    timeSaved: 'Variable',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 29,
    category: 'EMERGENCIAS',
    tool: 'Kit de Supervivencia Diaria',
    description: 'Protocolo para días completamente caóticos',
    prompt: 'Situación actual: [descripción caos], tiempo disponible: [X] minutos, prioridad absoluta hoy: [1 cosa], energía personal: [1-10]. Dame plan de supervivencia de 3 pasos que mantenga lo esencial funcionando.',
    timeSaved: '2 horas/crisis',
    urgency: 'CRÍTICA',
    implementation: '1 minuto setup',
  },
  {
    id: 30,
    category: 'EMERGENCIAS',
    tool: 'Solucionador de Crisis Infantiles',
    description: 'Respuesta inmediata a emergencias de crianza',
    prompt: 'Emergencia: [descripción situación], edad del niño: [X], ubicación: [casa/fuera], personas presentes: [quién]. Necesito protocolo inmediato paso a paso para manejar la situación de forma segura y calmada.',
    timeSaved: 'Variable',
    urgency: 'CRÍTICA',
    implementation: '30 segundos setup',
  },
  {
    id: 31,
    category: 'EMERGENCIAS',
    tool: 'Plan B Automático',
    description: 'Backup instantáneo para cuando todo falla',
    prompt: 'Qué falló: [situación], tiempo hasta obligación: [X] minutos, recursos disponibles: [lista mínima]. Genera plan B realista que funcione con recursos limitados y tiempo escaso.',
    timeSaved: '1 hora/crisis',
    urgency: 'CRÍTICA',
    implementation: '1 minuto setup',
  },
  {
    id: 32,
    category: 'EMERGENCIAS',
    tool: 'Gestor de Overwhelm Agudo',
    description: 'Protocolo para sobrecarga emocional extrema',
    prompt: 'Me siento: [emociones], síntomas físicos: [lista], situación desencadenante: [contexto], apoyo inmediato: [disponible/no]. Dame protocolo de 5 minutos para estabilizarme y plan de las próximas 2 horas.',
    timeSaved: 'Variable',
    urgency: 'CRÍTICA',
    implementation: '30 segundos setup',
  },
  {
    id: 33,
    category: 'EMERGENCIAS',
    tool: 'Activador de Red de Emergencia',
    description: 'Llamada de auxilio estructurada',
    prompt: 'Necesito ayuda urgente con: [específico], tiempo crítico: [cuándo], personas que podrían ayudar: [lista]. Prioriza contactos y dame scripts específicos para pedir ayuda efectivamente.',
    timeSaved: '30 min/crisis',
    urgency: 'CRÍTICA',
    implementation: '2 minutos setup',
  },
  {
    id: 34,
    category: 'EMERGENCIAS',
    tool: 'Simplificador Extremo',
    description: 'Reducción a lo absolutamente esencial',
    prompt: 'Todo está colapsando: [descripción], debo mantener: [obligaciones críticas], puedo posponer: [lista]. Identifica solo las 3 cosas más críticas para las próximas 24 horas y elimina todo lo demás.',
    timeSaved: 'Variable',
    urgency: 'CRÍTICA',
    implementation: '2 minutos setup',
  },
  {
    id: 35,
    category: 'DESARROLLO PROFESIONAL',
    tool: 'Optimizador de CV para Mamás',
    description: 'Adapta tu CV a roles flexibles o remotos',
    prompt: 'Soy madre, [X] años de experiencia en [campo], busco rol [flexible/remoto] como [puesto]. Mi último CV es: [pegar CV]. Adapta mi experiencia para destacar habilidades transferibles, minimizar brechas laborales y atraer a empresas pro-familia.',
    timeSaved: '4 horas/aplicación',
    urgency: 'MEDIA',
    implementation: '10 minutos setup',
  },
  {
    id: 36,
    category: 'DESARROLLO PROFESIONAL',
    tool: 'Preparador de Entrevistas',
    description: 'Simula entrevistas para roles pro-familia',
    prompt: 'Tengo entrevista para [puesto] en [empresa], descripción de puesto: [pegar]. Soy madre, mis prioridades son [flexibilidad, balance]. Simula la entrevista, hazme preguntas difíciles sobre mi brecha laboral y cómo gestionaré responsabilidades.',
    timeSaved: '3 horas/entrevista',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 37,
    category: 'DESARROLLO PROFESIONAL',
    tool: 'Generador de Ideas de Negocio',
    description: 'Encuentra negocios compatibles con la maternidad',
    prompt: 'Mis habilidades: [lista], pasiones: [lista], capital inicial: $[X], horas disponibles/semana: [X]. Genera 5 ideas de negocio que pueda empezar desde casa, con bajo riesgo y potencial de crecimiento mientras crío a mis hijos.',
    timeSaved: '10 horas/investigación',
    urgency: 'BAJA',
    implementation: '5 minutos setup',
  },
  {
    id: 38,
    category: 'DESARROLLO PROFESIONAL',
    tool: 'Asistente de Networking',
    description: 'Crea mensajes para conectar profesionalmente',
    prompt: 'Quiero conectar en LinkedIn con [nombre], [puesto] en [empresa]. Nuestro punto en común es [X]. Soy madre volviendo al mundo laboral en [campo]. Escribe un mensaje corto y memorable para iniciar una conversación profesional.',
    timeSaved: '15 min/contacto',
    urgency: 'BAJA',
    implementation: '2 minutos setup',
  },
  {
    id: 39,
    category: 'DESARROLLO PROFESIONAL',
    tool: 'Plan de Aprendizaje Personalizado',
    description: 'Diseña una ruta para adquirir nuevas habilidades',
    prompt: 'Quiero aprender [habilidad] para reincorporarme a [industria]. Tengo [X] horas/semana, presupuesto $[X], mi estilo de aprendizaje es [visual/práctico]. Crea un plan de 3 meses con recursos online (cursos, podcasts, libros).',
    timeSaved: '5 horas/planificación',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 40,
    category: 'DESARROLLO PROFESIONAL',
    tool: 'Optimizador de Perfil de LinkedIn',
    description: 'Mejora tu perfil para atraer reclutadores',
    prompt: 'Mi perfil de LinkedIn: [link]. Soy madre buscando reingresar a [campo]. Optimiza mi titular, resumen y experiencia para destacar mis fortalezas, justificar mi pausa profesional y usar palabras clave para [puestos deseados].',
    timeSaved: '2 horas',
    urgency: 'MEDIA',
    implementation: '10 minutos setup',
  },
  {
    id: 41,
    category: 'FINANZAS PERSONALES',
    tool: 'Analista de Gastos "Hormiga"',
    description: 'Identifica y reduce pequeños gastos recurrentes',
    prompt: 'Mis categorías de gastos mensuales son: [lista con montos]. No sé a dónde se va el dinero. Analiza estos gastos, identifica 5 "gastos hormiga" y sugiere alternativas o recortes que ahorren al menos $[X] al mes sin afectar mi calidad de vida familiar.',
    timeSaved: '2 horas/mes',
    urgency: 'MEDIA',
    implementation: '10 minutos setup',
  },
  {
    id: 42,
    category: 'FINANZAS PERSONALES',
    tool: 'Planificador de Ahorro para Hijos',
    description: 'Estrategias para el futuro educativo de tus hijos',
    prompt: 'Tengo [X] hijos de [edades]. Mi capacidad de ahorro mensual es $[X]. Quiero empezar a ahorrar para su educación universitaria. Compara opciones como [cuenta de ahorros, fondo de inversión, etc.] y sugiere la mejor estrategia para mi perfil de riesgo [conservador/moderado/agresivo].',
    timeSaved: '5 horas/investigación',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 43,
    category: 'FINANZAS PERSONALES',
    tool: 'Negociador de Facturas y Suscripciones',
    description: 'Genera guiones para reducir gastos fijos',
    prompt: 'Mis suscripciones mensuales son: [lista con precios]. Mi factura de [servicio, ej: internet] es de $[X]. Genera un guion para llamar a [proveedor] y negociar una tarifa más baja, y ayúdame a decidir qué 3 suscripciones eliminar según su uso y costo-beneficio.',
    timeSaved: '1 hora/negociación',
    urgency: 'ALTA',
    implementation: '5 minutos setup',
  },
  {
    id: 44,
    category: 'FINANZAS PERSONALES',
    tool: 'Asesor de Ingresos Extra',
    description: 'Ideas para generar ingresos en tu tiempo libre',
    prompt: 'Soy madre, mis habilidades son [lista], tengo [X] horas libres a la semana [especificar horarios]. Sugiere 3 formas realistas de generar ingresos extra desde casa, con un plan de acción para empezar cada una y una estimación de ingresos potenciales.',
    timeSaved: '8 horas/investigación',
    urgency: 'MEDIA',
    implementation: '5 minutos setup',
  },
  {
    id: 45,
    category: 'FINANZAS PERSONALES',
    tool: 'Simulador de Metas Financieras',
    description: 'Visualiza cómo alcanzar tus objetivos económicos',
    prompt: 'Mi meta es [ej: dar el enganche de una casa] de $[X] en [Y] años. Mis ingresos son $[X] y mis ahorros actuales son $[X]. Crea un plan de ahorro mensual, sugiere ajustes en mi presupuesto y calcula si la meta es realista. De no serlo, ¿qué variables debo ajustar?',
    timeSaved: '3 horas/planificación',
    urgency: 'BAJA',
    implementation: '5 minutos setup',
  },
  {
    id: 46,
    category: 'FINANZAS PERSONALES',
    tool: 'Educador Financiero para Niños',
    description: 'Crea lecciones de dinero para tus hijos',
    prompt: 'Quiero enseñar a mi hijo de [edad] sobre [concepto financiero, ej: el ahorro, el valor del dinero]. Su personaje favorito es [X]. Crea una historia corta o una actividad lúdica que le enseñe este concepto de forma divertida y fácil de entender.',
    timeSaved: '1 hora/lección',
    urgency: 'BAJA',
    implementation: '2 minutos setup',
  },
];
